"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { FileText, Download, FileBarChart2, AlertTriangle, Cpu, Activity, Lightbulb, Shield } from "lucide-react";

const pages = [
  {
    num: 1, icon: FileBarChart2, color: "text-accent", title: "Executive Summary",
    content: [
      { label: "Report Date", value: new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) },
      { label: "Overall Efficiency", value: "94.2% — Above Target" },
      { label: "AI Health Score", value: "Optimal (87/100)" },
      { label: "Critical Alarms (Active)", value: "0 — All Acknowledged" },
      { label: "Energy Consumption", value: "4.20 MWh — Below Threshold" },
      { label: "Production Output", value: "8,450 / 10,000 units (84.5%)" },
      { label: "Systems Online", value: "5 / 6 nodes — 1 Warning (NW-Core)" },
      { label: "AI Anomaly Score", value: "Current: 30 — Normal Range" },
    ]
  },
  {
    num: 2, icon: Cpu, color: "text-warning", title: "Predictive Maintenance Forecast",
    content: [
      { label: "Conveyor Belt Motor M-101", value: "Health: 92% · 720h until failure · Confidence: 98%" },
      { label: "Cooling Tower Fan F-02", value: "Health: 45% · 48h until failure · Confidence: 94% ⚠️ URGENT" },
      { label: "Main Compressor C-A", value: "Health: 88% · 500h until failure · Confidence: 89%" },
      { label: "Boiler Unit B-01", value: "Health: 76% · Routine maintenance in 30 days" },
      { label: "AI Recommendation #1", value: "Schedule emergency inspection of Cooling Tower Fan F-02 within 24 hours." },
      { label: "AI Recommendation #2", value: "Pre-order bearings for Motor M-101 to minimize downtime at 720h mark." },
    ]
  },
  {
    num: 3, icon: Activity, color: "text-critical", title: "Telemetry & Vibration Analysis",
    content: [
      { label: "Pump 3A — Status", value: "Critical — Vibration exceeding baseline by 48%" },
      { label: "Vibration Peak (10:24 AM)", value: "590 mm/s² — Critical threshold: 600 mm/s²" },
      { label: "Temperature (Average)", value: "72.4°C — Within normal range (< 80°C)" },
      { label: "Pressure (Average)", value: "3.8 bar — Normal (warn: 4.5 bar)" },
      { label: "Voltage (Line 1)", value: "415V — Nominal (±5% tolerance)" },
      { label: "AI Analysis", value: "Vibration spike pattern consistent with bearing wear. Recommend immediate inspection of Pump 3A before next production cycle." },
    ]
  },
  {
    num: 4, icon: Shield, color: "text-safe", title: "Security & User Activity Audit",
    content: [
      { label: "Login Event", value: "Operator 'Alex Chen' authenticated at 08:00 AM" },
      { label: "Role Used", value: "Lead Operator → switched to Plant Manager at 10:45 AM" },
      { label: "Layout Change", value: "Dashboard Layout Editor activated at 10:45 AM — 2 widgets repositioned" },
      { label: "Alarms Acknowledged", value: "3 alarms acknowledged by Plant Manager role" },
      { label: "AI Copilot Sessions", value: "1 session — Query: 'Create Cooling System Overview'" },
      { label: "Settings Changes", value: "Temperature threshold adjusted to 80°C · Sound notifications disabled" },
    ]
  },
  {
    num: 5, icon: Lightbulb, color: "text-purple-400", title: "AI Strategic Recommendations",
    content: [
      { label: "Priority 1", value: "CRITICAL: Inspect and replace Cooling Tower Fan F-02 within 24h (Confidence: 94%)" },
      { label: "Priority 2", value: "WARNING: Investigate Pump 3A vibration before next production cycle (Confidence: 98%)" },
      { label: "Priority 3", value: "OPTIMIZE: Reconfigure shift schedule to reduce off-peak energy waste by ~0.5 MWh/day" },
      { label: "Priority 4", value: "PLAN: Pre-order M-101 bearing kit for scheduled maintenance in 30 days" },
      { label: "Priority 5", value: "MONITOR: Network Switch NW-Core running at 78% CPU — consider load balancing" },
      { label: "Projected Savings", value: "Implementing all recommendations could reduce unplanned downtime by ~62% over 90 days." },
    ]
  },
];

export default function ReportsPage() {
  const [activePage, setActivePage] = useState(0);

  const handleDownload = () => {
    const lines: string[] = [
      "# NeuroHMI — Comprehensive 5-Page AI Analysis Report",
      `Generated: ${new Date().toLocaleString()}`,
      "---",
    ];
    pages.forEach(p => {
      lines.push(`\n## Page ${p.num}: ${p.title}`);
      p.content.forEach(row => lines.push(`- **${row.label}:** ${row.value}`));
    });
    lines.push("\n---\n_Report generated by NeuroHMI AI Engine. For authorized personnel only._");
    const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `NeuroHMI-Report-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const page = pages[activePage];

  return (
    <div className="p-8 flex flex-col gap-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3"><FileText className="w-7 h-7 text-accent" />AI Generated Reports</h1>
          <p className="text-zinc-400 mt-1">5-page comprehensive analysis — preview and download</p>
        </div>
        <button onClick={handleDownload}
          className="px-5 py-2.5 rounded-xl bg-accent text-black font-bold text-sm flex items-center gap-2 hover:bg-accent-hover transition-all shadow-[0_0_20px_rgba(14,165,233,0.3)] hover:shadow-[0_0_30px_rgba(14,165,233,0.5)]">
          <Download className="w-5 h-5" /> Download Report (.md)
        </button>
      </div>

      {/* Page Tabs */}
      <div className="flex gap-2 overflow-x-auto pb-1">
        {pages.map((p, i) => (
          <button key={i} onClick={() => setActivePage(i)}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium whitespace-nowrap transition-all border ${activePage === i ? "bg-accent/10 border-accent/40 text-accent" : "border-white/5 text-zinc-400 hover:text-white bg-white/2"}`}>
            <p.icon className={`w-4 h-4 ${p.color}`} />
            Page {p.num}
          </button>
        ))}
      </div>

      {/* Report Preview */}
      <motion.div key={activePage} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
        className="glass-panel rounded-2xl p-8 border border-white/5">
        <div className="flex items-center gap-4 mb-6 pb-6 border-b border-white/10">
          <div className={`w-12 h-12 rounded-2xl bg-white/5 flex items-center justify-center`}>
            <page.icon className={`w-6 h-6 ${page.color}`} />
          </div>
          <div>
            <div className="text-xs text-zinc-500 uppercase tracking-widest">Page {page.num} of 5</div>
            <h2 className="text-xl font-bold text-white">{page.title}</h2>
          </div>
          <div className="ml-auto text-xs text-zinc-600 font-mono">NeuroHMI AI Report · {new Date().toLocaleDateString()}</div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {page.content.map((row, i) => (
            <div key={i} className="p-4 rounded-xl bg-black/30 border border-white/5">
              <div className="text-xs text-zinc-500 uppercase tracking-wider mb-1">{row.label}</div>
              <div className={`text-sm font-medium ${row.value.includes("URGENT") || row.value.includes("CRITICAL") ? "text-critical" : row.value.includes("WARNING") ? "text-warning" : "text-white"}`}>{row.value}</div>
            </div>
          ))}
        </div>

        <div className="mt-6 flex justify-between text-xs text-zinc-600 border-t border-white/5 pt-4">
          <span>NeuroHMI Industrial Control System · Confidential</span>
          <span>Page {page.num} / 5</span>
        </div>
      </motion.div>

      {/* Page Navigation */}
      <div className="flex justify-between">
        <button onClick={() => setActivePage(p => Math.max(0, p - 1))} disabled={activePage === 0}
          className="px-4 py-2 rounded-xl border border-white/10 text-sm text-zinc-400 hover:text-white disabled:opacity-30 transition-all">← Previous Page</button>
        <button onClick={() => setActivePage(p => Math.min(pages.length - 1, p + 1))} disabled={activePage === pages.length - 1}
          className="px-4 py-2 rounded-xl border border-white/10 text-sm text-zinc-400 hover:text-white disabled:opacity-30 transition-all">Next Page →</button>
      </div>
    </div>
  );
}
